#!/usr/bin/env sh

# setbg &		# Set the background
# Switch to US international with Caps as Mod/Escape
setxkbmap -option ctrl:swap_lalt_lctl,caps:escape &
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
